version: '3.7'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: Asde71.4
      POSTGRES_USER: postgres
      POSTGRES_ROOT_PASSWORD: Asde71.4
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5452:5432
    volumes:
      - ./datos/db:/var/lib/postgresql/data/pgdata
  web:
    build: web
    restart: always
    ports:
      - 100:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: db
      REDMINE_DB_PASSWORD: Asde71.4
      TZ: America/Bogota
    volumes:
      - ./datos/files:/usr/src/redmine/files
      - ./datos/themes/PurpleMine2:/usr/src/redmine/public/themes/PurpleMine2
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 5453:8080